(define (make-frame variables values)
  (define (make-frame-iter variables values)
      (if (null? variables)
              '()
                      (cons (cons (car variables)
                                          (car values))
                                    (make-frame-iter (cdr variables)
                                                                   (cdr values)))))
    (make-frame-iter variables values))

(define (frame-variables frame)
  (if (null? frame)
        '()
              (cons (caar frame)
                          (frame-variables (cdr frame)))))

(define (frame-values frame)
  (if (null? frame)
        '()
              (cons (cdar frame)
                          (frame-values (cdr frame)))))

(define (add-binding-to-frame! var val frame)
  (set-cdr! frame (cons (cons var val) (cdr frame))))
