(use gauche.test)
(load "./2.3.3-1.scm")

;(trace element-of-set?)
;(trace adjoin-set)
(test-start "2.3.3 例:集合の表現")
(test-section "順序づけられないリストとしての集合")
(test-section "element-of-set?")
(test* "(element-of-set? 'a '(a b c))" true (element-of-set? 'a '(a b c)))
(test* "(element-of-set? 'z '(a b c))" false (element-of-set? 'z '(a b c)))
(test-section "adjoin-set")
(test* "(adjoin-set 'z '(a b c))" '(z a b c) (adjoin-set 'z '(a b c)))
(test* "(adjoin-set 'a '(a b c))" '(a b c) (adjoin-set 'a '(a b c)))
(test-section "intersection-set")
(test* "(intersection-set '(a b c) '(b c d))" '(b c) (intersection-set '(a b c) '(b c d)))
(test* "(intersection-set '(a b c) '(hoge fuga))" '() (intersection-set '(a b c) '(hoge fuga)))
(test-end)
